'\" -*- coding: us-ascii -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH flashmq 1 "3 February 2023" "" ""
.SH NAME
flashmq \- A fast light-weight scalable MQTT server
.SH SYNOPSIS
'nh
.fi
.ad l
\fBflashmq\fR \kx
.if (\nx>(\n(.l/2)) .nr x (\n(.l/5)
'in \n(.iu+\nxu
[-h | --help] [-v | --version] [-l | --license]
.br
[
-c | --config-file 
\fIconfig_file_path\fR
] [-t | --test-config]
'in \n(.iu-\nxu
.ad b
'hy
.SH DESCRIPTION
FlashMQ is a MQTT 3.1, 3.1.1 and 5 broker designed to be light-weight and handle millions of clients and/or messages.
.SH AUTHOR
Wiebe Cazemier <\*(T<contact@flashmq.org\*(T>>.
.SH "SEE ALSO"
\fBflashmq.conf\fR(5)
, 
.URL https://www.flashmq.org/ www.flashmq.org
