#!/bin/bash -e

if [[ ! -f /etc/lsb-release && ! -f /etc/debian_version ]]; then
  echo "This is not a Debian or Ubuntu based system? Hmm"
  exit 1
fi

if ! command -v systemctl -v &> /dev/null; then
  echo "This is not a systemd-based system. File a bug-report at https://github.com/halfgaar/FlashMQ/issues"
  exit 1
fi
