name: Testing
on: [push]
jobs:
  compilation:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            friendly: clang
            SPEC: linux-clang
            aptpkg: clang
          - os: ubuntu-22.04
            friendly: gcc
            SPEC: linux-g++
            aptpkg: build-essential
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: FlashMQTests
    name: "${{ matrix.friendly }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: sudo apt update
      # Build prerequisites
      - run: sudo apt install -y cmake libssl-dev qtbase5-dev ${{ matrix.aptpkg }}
      # Building
      - run: qmake -spec "${{ matrix.SPEC }}" FlashMQTestsMeta.pro
      - run: make
      # Let's-a-go
      - run: ./FlashMQTests
